name: remote ssh command
on:
  push:
    branches: [deploy]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/summoner/
          git pull
          git submodule sync
          git submodule update
          git submodule statu
